name: Build and Deploy Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy Dist to Deploy Branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Save dist folder before switching branches
          cp -r dist ../dist-temp

          # Switch to deploy branch (create if not exists)
          git fetch origin
          git checkout deploy || git checkout --orphan deploy

          # Clear old files
          rm -rf ./*

          # Copy new build files
          cp -r ../dist-temp/* .

          # Commit and push
          git add .
          git commit -m "Deploy build from GitHub Actions" || echo "No changes to commit"
          git push git@github.com:easvera25/easvera.git deploy --force

